[project]
name = "poem-scraping"
version = "0.1.0"
description = "Bangla Poetry Web Scraper for Nazrul Rachanabali"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "parsel>=1.10.0",
    "requests>=2.32.5",
]
